name: add-new-version
on:
  workflow_call:
    inputs:
      repository:
        description: 'repository choice'
        required: true
        default: 'TexTransTool'
        type: string
      tag:
        type: string
        required: true
        description: 'version tag string'
  workflow_dispatch:
    inputs:
      repository:
        description: 'repository choice'
        required: true
        default: 'TexTransTool'
        type: choice
        options:
          - TexTransTool
          - TexTransCore
          - TTT-DestructiveTextureUtilities
          - TTT-WorldExtension
          - ReinaS-lilToonNDMFUtility
          - TTCE-Wgpu
      tag:
        type: string
        required: true
        description: 'version tag string'

jobs:
  add-new-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get NewVersion Data
        id: ReleaseData
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repo: ReinaS-64892/${{ inputs.repository }}
          tag: ${{ inputs.tag }}

      - name: AddToVPMDotJson
        id: AddToVPMDotJson
        env:
          Assets: ${{ steps.ReleaseData.outputs.assets }}
          Tag: ${{ inputs.tag }}
        run: |
          cd .github/workflows/AddPackageToRepo
          dotnet run ../../../vpm.json

      - name: git commit
        env:
          REPO: ${{ inputs.repository }}
          TAG: ${{ inputs.tag }}
        run: |
          git config user.name  "GitHub Action"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./vpm.json
          git commit -m "Add $REPO New Version $TAG!"
          git push origin
