name: add-new-version
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'repository choice'
        required: true
        default: 'TexTransTool'
        type: choice
        options:
          - TexTransTool
          - TTT-DestructiveTextureUtilities
          - TTT-WorldExtension
      tag:
        type: string
        required: true
        description: 'version tag string'

jobs:
  add-new-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: MoveToVar
        id: VPMRepoJson
        run: |
          Temp=`cat ./vpm.json`
          echo 'result=' $Temp >> "$GITHUB_OUTPUT"


      - name: Get NewVersion Data
        id: ReleaseData
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repo: ReinaS-64892/${{ github.event.inputs.repository }}
          tag: ${{ github.event.inputs.tag }}

      - name: Get ZipURL
        id: ZipURL
        uses: actions/github-script@v7
        env:
          Assets: ${{ steps.ReleaseData.outputs.assets }}
          Tag: ${{ github.event.inputs.tag }}
        with:
          result-encoding: string
          script: require(".github/workflows/JsScripts/GetZipURL.js")

      - name: GetPackageDotJson
        id: PackageDotJson
        uses: actions/github-script@v7
        env:
          Assets: ${{ steps.ReleaseData.outputs.assets }}
        with:
          result-encoding: string
          script: |
            import { Func } from "./.github/workflows/JsScripts/GetPackageDotJson.mjs";
            Func();


      - name: Debug
        run: |
          echo ${{ steps.ZipURL.outputs.result }}
          echo ${{ steps.PackageDotJson.outputs.result }}


      - name: ReplacePackageURL
        id: ReplacedPackageJson
        uses: actions/github-script@v7
        env:
          PackageJson: ${{ steps.PackageDotJson.outputs.result }}
          ReplaceURL: ${{ steps.ZipURL.outputs.result }}
        with:
          result-encoding: string
          script: require(".github/workflows/JsScripts/ReplacePackageURL.js")

      - name: AddVPMDotJson
        id: AddedVPMDotJson
        uses: actions/github-script@v7
        env:
          VPMRepoJson: ${{ steps.VPMRepoJson.outputs.result }}
          AddPackageJson: ${{ steps.ReplacedPackageJson.outputs.result }}
        with:
          result-encoding: string
          script: require(".github/workflows/JsScripts/AddToVPMRepo.js")


      - name: Write Json
        run: |
          rm  ./vpm.json
          echo ${{ steps.AddedVPMDotJson.outputs.result }} >> ./vpm.json

      - name: git commit
        run: |
          git config user.name  "GitHub Action"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./vpm.json
          git commit -m "Add ${{ github.event.inputs.repository }} New Version ${{ github.event.inputs.tag }}!"
          git push origin
