name: add-ttt-new-version
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true


jobs:
  add-ttt-new-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get NewVarsion Data
        id: RereaseData
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repo: ReinaS-64892/TexTransTool
          tag: ${{ github.event.inputs.tag }}
      - name: Debug
        run: |
          pwd
          ls -alh
          cat  ${{ steps.RereaseData.outputs.assets }}
      - name: GetPackege.json
        run: wget ${{ steps.RereaseData.outputs.assets }}
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: ./VpmRepo
      - name: Debug
        run: |
          pwd
          ls -alh
      # - name: replace version
      #   run: |
      #    cd ./VpmRepo
      #    tempjson='mktemp'
      #    withoutvtagstr=`echo ${{ github.event.inputs.tag }} | sed -e "s/^v//"`
      #    jq ".version|=\"${withoutvtagstr}\"" ./package.json > $tempjson
      #    mv $tempjson ./package.json
      # - name: git commit
      #   run: |
      #     git config user.name  "GitHub Action"
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git add ./vpm.json
      #     git commit -m "Add TTT New Version ${{ github.event.inputs.tag }}!!"
      #     git tag ${{ github.event.inputs.tag }}
      #     git push
      #     git push origin ${{ github.event.inputs.tag }}
