name: add-ttt-we-new-version
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  add-ttt-du-new-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get NewVarsion Data
        id: ReleaseData
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repo: ReinaS-64892/TTT-WorldExtension
          tag: ${{ github.event.inputs.tag }}
